---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.5.1
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/etc/alertmanager/alertmanager.yml
        - -web.listen-address=:80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
